-- AUTO-GENERATED BY igluctl DO NOT EDIT
-- Generator: igluctl 0.4.1
-- Generated: 2018-09-23 12:59 UTC

CREATE SCHEMA IF NOT EXISTS atomic;

CREATE TABLE IF NOT EXISTS atomic.com_what3words_reverse_geocoding_context_1 (
    "schema_vendor"        VARCHAR(128)     ENCODE ZSTD NOT NULL,
    "schema_name"          VARCHAR(128)     ENCODE ZSTD NOT NULL,
    "schema_format"        VARCHAR(128)     ENCODE ZSTD NOT NULL,
    "schema_version"       VARCHAR(128)     ENCODE ZSTD NOT NULL,
    "root_id"              CHAR(36)         ENCODE RAW  NOT NULL,
    "root_tstamp"          TIMESTAMP        ENCODE ZSTD NOT NULL,
    "ref_root"             VARCHAR(255)     ENCODE ZSTD NOT NULL,
    "ref_tree"             VARCHAR(1500)    ENCODE ZSTD NOT NULL,
    "ref_parent"           VARCHAR(255)     ENCODE ZSTD NOT NULL,
    "bounds.northeast.lat" DOUBLE PRECISION ENCODE RAW,
    "bounds.northeast.lng" DOUBLE PRECISION ENCODE RAW,
    "bounds.southwest.lat" DOUBLE PRECISION ENCODE RAW,
    "bounds.southwest.lng" DOUBLE PRECISION ENCODE RAW,
    "crs.properties.href"  VARCHAR(4096)    ENCODE ZSTD,
    "crs.properties.type"  VARCHAR(4096)    ENCODE ZSTD,
    "crs.type"             VARCHAR(4096)    ENCODE ZSTD,
    "geometry.lat"         DOUBLE PRECISION ENCODE RAW,
    "geometry.lng"         DOUBLE PRECISION ENCODE RAW,
    "language"             VARCHAR(4096)    ENCODE ZSTD,
    "map"                  VARCHAR(4096)    ENCODE ZSTD,
    "status.code"          BIGINT           ENCODE ZSTD,
    "status.message"       VARCHAR(4096)    ENCODE ZSTD,
    "thanks"               VARCHAR(4096)    ENCODE ZSTD,
    "words"                VARCHAR(4096)    ENCODE ZSTD,
    FOREIGN KEY (root_id) REFERENCES atomic.events(event_id)
)
DISTSTYLE KEY
DISTKEY (root_id)
SORTKEY (root_tstamp);

COMMENT ON TABLE atomic.com_what3words_reverse_geocoding_context_1 IS 'iglu:com.what3words/reverse_geocoding_context/jsonschema/1-0-0';
